### ISSUE TITLE
AccountDuplication step of Login flow fails at first attempt. After some attempts, it works as usual

### ISSUE THREAD

**Issue by Rishikant181** [Rishikant181/Rettiwt-API#290]

**Comment by seiya-git** [comment]
For me, it's asking for entering confirmation code 
and AccountDuplication step will fail because there is no 'Set-Cookie' header

**Comment by Rishikant181** [comment]
@seiya-git The issue that this thread addresses has been fixed a long time ago (I forgot to close this, my bad :P).

Coming to your issue, can you login from the browser?

**Comment by seiya-git** [comment]
@Rishikant181 yes, from browser I can login

**Comment by Rishikant181** [comment]
@seiya-git 
1. Does it ever ask for confirmation in the browser?
2. Which version of this package are you on?

**Comment by seiya-git** [comment]
@Rishikant181
1. yes, subtask_id: "LoginAcid"
2. 1.4.0

**Comment by seiya-git** [comment]
For entering confirmation code:
URL: https://api.twitter.com/1.1/onboarding/task.json
body:
```
{"flow_token":"${FLOWTOKEN}","subtask_inputs":[{"subtask_id":"LoginAcid","enter_text":{"text":"${CONFIRMATIONCODE}","link":"next_link"}}]}
```

**Comment by Rishikant181** [comment]
@seiya-git Logging in too many times is bound to raise suspicions, that's why Twitter might be asking you to confirm whether it really is your account.

The recommended approach is to login once and store the cookies that you get somewhere safe (such as environment variable) and pass on those cookies to Rettiwt from the environment itself.

Remember: The cookies you get after logging in are valid for a year. So, login once and use the same cookies everytime.
