### ISSUE TITLE
Filtered-stream

### ISSUE THREAD

**Issue by maziyarpanahi** [Rishikant181/Rettiwt-API#295]
Amazing work!

I wonder if anyone has started working on simulating (somehow) the `Filtered-Stream` API where you could follow users/keywords etc. in real-time?

**Comment by Rishikant181** [comment]
I haven't actually even heard of filtered stream on Twitter, but looking into it, it might be worth giving a shot, but I don't think it's possible. I'll check it out and confirm.

Thanks for the feedback bud!

**Comment by Rishikant181** [comment]
There seems to be no way of getting filtered-streams unfortunately, since it's not used on the Twitter web app.
