### ISSUE TITLE
Stopped working - "Error: Forbidden"

### ISSUE THREAD

**Issue by jonaslsaa** [Rishikant181/Rettiwt-API#297]
Everything has been working until now, on the 20.04. the library stopped working.
I am using the NPM package using a guest session.
Error:
`error - Error: Forbidden
    at FetcherService.handleHTTPError (/Users/myapp/node_modules/rettiwt-api/dist/services/util/FetcherService.js:123:19)
    at /Users/myapp/node_modules/rettiwt-api/dist/services/util/FetcherService.js:178:123 {
  page: '/api/myapp/fetch'
}`

My code using the library:
```js
  const rettiwt = Rettiwt();  // seems to fail here ?
  const tweetService = rettiwt.tweets;
  const tweetFilter = new TweetFilter({fromUsers: usersToScrapeList, startDate: startOfSearch.toISOString()});
  const tweetBatch: {next: {value: string}, list: Tweet[]} = await tweetService.getTweets(tweetFilter, 18, nextCursor);
```

**Comment by Rishikant181** [comment]
This is an issue that has come up just now. I'm working on fixing it.

**Comment by Rishikant181** [comment]
Okay, I have some news.

First, twitter has blocked access to their advanced search feature for guest users. Therefore no more fetching tweets using the advanced search, without logging in.

Second (and slightly good), there is a way to circumvent this problem by fetching tweets from user's profile page instead of using the advanced search.

I'll be working on the second option.

**Comment by jonaslsaa** [comment]
Amazing
> Second (and slightly good), there is a way to circumvent this problem by fetching tweets from user's profile page instead of using the advanced search.
> 
> I'll be working on the second option.

That sounds perfect, for my use case at least. Will the library API change?

**Comment by Rishikant181** [comment]
@TheVoxcraft So the issue has been resolved (for now).

You can still older method defined here https://rishikant181.github.io/Rettiwt-API/classes/TweetService.html#getTweets to fetch tweets using a filter, but it now requires you to use credentials.

If you don't wan to use credentials, then you can use this new method defined here https://rishikant181.github.io/Rettiwt-API/classes/UserService.html#getUserTweets. However, this method does not allow advanced tweet querying.

If you face any further issues, feel free to contact!
