### ISSUE TITLE
getTweets not working - "Error: BadRequest"

### ISSUE THREAD

**Issue by jonaslsaa** [Rishikant181/Rettiwt-API#305]
The login method for getting tweets was working great for a few days, now it is no longer working. I've tried using the same tokens and also logging each time, both give me the following error:
```
Server Error
Error: BadRequest

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
FetcherService.handleHTTPError
./node_modules/rettiwt-api/dist/services/util/FetcherService.js (123:19)
<unknown>
./node_modules/rettiwt-api/dist/services/util/FetcherService.js (178:123)
```
It occurs when trying to get a batch of tweets from accounts using `tweetService.getTweets` with a filter.
Code snippet:
```ts
const loginDetails = await Rettiwt().account.login(env.TW_EMAIL, env.TW_USERNAME, env.TW_PASSWORD);
console.log('Logged in to Twitter');
const rettiwt = Rettiwt(loginDetails);
const tweetService = rettiwt.tweets;
const tweetFilter = new TweetFilter({fromUsers: usersToScrapeList, startDate: startOfSearch.toISOString()});
console.log('Fetching tweets from ' + startOfSearch.toISOString());
const tweets: MyTweet[] = [];
let nextCursor: string | undefined = undefined;
let i = 0;
do {
  await new Promise(r => setTimeout(r, 1000)); // Sleep for 1 second between batches
  // ERROR: BadRequest - following line crashes
  const tweetBatch: {next: {value: string}, list: Tweet[]} = await tweetService.getTweets(tweetFilter, 18, nextCursor);
...
```

**Comment by Rishikant181** [comment]
Due to changes in Twitter APIs, we had to make some necessary changes in the package too. Please update to the latest version and see if the issue persists.

**Comment by jonaslsaa** [comment]
Looks like I am using the latest version on npm, 1.1.8

**Comment by Rishikant181** [comment]
Can you check if any data actually gets stored in loginDetails?

**Comment by jonaslsaa** [comment]
Yes, data seems valid, in following format:
```js
{
  kdt: '...',
  twid: '"..."',
  ct0: '...',
  auth_token: '...'
}
```

**Comment by jonaslsaa** [comment]
What I've tried:
- Reducing number of users in filter
- Removing startDate argument
- Using default count on `getTweets` (by setting to undefined)
- Using login and login tokens
- Delay before doing query
- Using direct on object syntax:
```js
await Rettiwt(loginDetails).tweets.getTweets(tweetFilter, 18, nextCursor);
```
None worked.

**Comment by Rishikant181** [comment]
What is the tweet filter you are using?

**Comment by Rishikant181** [comment]
Can you provide the userToScrape list and startOfSearch for debug purpose?

It seems there might be some issue related to request data not being available or something like that. So without the data set, it will not be possible to reproduce the issue

**Comment by jonaslsaa** [comment]
These are the filters
```js
{
  "fromUsers": [
    "politietsorost",
    "oslopolitiops",
    "politietost",
    "politietsorvest",
    "politiagder",
    "politiinnlandet",
    "politinordland",
    "politifinnmark",
    "PolitiTrondelag",
    "PolitiMRpd",
    "politivest",
    "polititroms",
    "110Vest",
    "110Bodo",
    "110Innlandet",
    "sorost110",
    "Oslo110sentral",
    "110sorvest",
    "110agder"
  ],
  "startDate": "2023-05-04T03:58:54.095Z"
}
```

**Comment by Rishikant181** [comment]
Sorry for the late reply.
I was busy with my semester exams and thankfully, I'm not dead (yet) /s.

I tried to replicate this, but (un)fortunately, this works on my pc. Did you try logging in to you Twitter account from the browser to see whether you can log in?

**Comment by jonaslsaa** [comment]
No worries! There is no problem logging in to my account on the website.
I'll look into it more closely soon (a few days left of my semester), is there anything else I should test then?
