### ISSUE TITLE
POST likes

### ISSUE THREAD

**Issue by zk118** [Rishikant181/Rettiwt-API#308]
Hey, thanks for the awesome lib !
I was wondering if it is possible to POST likes to specific tweets ?
And if not, how could I achieve it ?

Thank you in advance.

**Comment by Rishikant181** [comment]
I am testing functionality to post content to Twitter (tweets, likes, replies, etc) and although it is possible, it is yet to be implemented, because the moment POSTING functionality is added, it is bound attract Twitter's attention.

Although, a separated add-in package is possible ;)
