### ISSUE TITLE
Get user retweets that aren't quote tweets

### ISSUE THREAD

**Issue by vincanger** [Rishikant181/Rettiwt-API#339]
with the recent changes, `twitter.tweets.getTweets()` does not return RT's from the user. Is there any method or way to fetch the tweets that they retweet?

**Comment by Rishikant181** [comment]
Yes! You can set 'links' field of the tweet filter to true. This will fetch retweets along with normal tweets and replies.

**Comment by vincanger** [comment]
ah! it would be cool to update the comments to reflect that. I assumed links were only hyperlinks, although I guess RT's are displayed as links...

thanks
