### ISSUE TITLE
Cannot set properties of undefined (setting 'tweet')

### ISSUE THREAD

**Issue by TheUltimateAbsol** [Rishikant181/Rettiwt-API#352]
Ok, this is probably just my stupidity, but I can't seem to initialize the module for the love of me.

All I have done is just done these lines
```
import { Rettiwt } from "rettiwt-api";
const API_KEY='some-cookie-value'
const rettiwt = Rettiwt(API_KEY);
```
whereas `some-cookie-value` is the value of the `cookie` line from the cli command `login <email> <username> <password>` using the Rettiwt-Auth package globally. (The CRSF token and the Bearer token were discarded... did I need these for something...?)

```
TypeError: Cannot set properties of undefined (setting 'tweet')
    at Rettiwt (/mnt/c/Users/thebe/Documents/like-counter/node_modules/rettiwt-api/dist/Rettiwt.js:24:20)
    at file:///mnt/c/Users/thebe/Documents/like-counter/getTweets.js:6:17
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

What am I doing wrong here? This is where I get called out for not being a javascript dev I guess...

**Comment by Rishikant181** [comment]
@TheUltimateAbsol What is the data that you are trying to fetch?

**Comment by TheUltimateAbsol** [comment]
basic user info and tweets from a user

```
rettiwt.user.details('username')
.then(details => {
	console.log(details)
})
.catch(error => {
    console.error("error fetching details")
})


rettiwt.tweet.search({
	fromUsers: ['username'],
})
.then(data => {
	console.log(data)
})
.catch(err => {
	console.error("help I failed")
})
```

**Comment by TheUltimateAbsol** [comment]
But the aforementioned error occurs before I get to that code. I am using NodeJS 18.14.2

**Comment by Rishikant181** [comment]
@TheUltimateAbsol I need the username whose tweets you are trying to fetch to reproduce the error

**Comment by TheUltimateAbsol** [comment]
@Rishikant181 `alkalinedd`

**Comment by Rishikant181** [comment]
> const rettiwt = Rettiwt(API_KEY);

Oops, this a minor mistake in my documentation.

This is the proper way to initialize a new Rettiwt instance:
```const rettiwt = new Rettiwt(API_KEY);```
