### ISSUE TITLE
Is it possible to fetch the number of views or bookmarks on a tweet?

### ISSUE THREAD

**Issue by TheUltimateAbsol** [Rishikant181/Rettiwt-API#354]
These are relatively new fields on twitter posts. I'm not sure if they are inaccessible with the current API or just not implemented.

![image](https://github.com/Rishikant181/Rettiwt-API/assets/28760461/d5b2bdd2-6bde-4823-bea8-9ed0960c2df9)

**Comment by Rishikant181** [comment]
Views and bookmarks are accessible and will be implemented soon. Thanks for the feedback!
