### ISSUE TITLE
Is there any sense for how long the cookies last?

### ISSUE THREAD

**Issue by nicholasg97** [Rishikant181/Rettiwt-API#364]
This isn't really an issue more of a general question regarding how long the cookies are good for after using rettiwt-auth? Just would be helpful to know for engineering my project, are we talking an hour, day, month, longer?

**Comment by Rishikant181** [comment]
When using rettiwt-auth, the cookies issued by Twitter have an expiry period of a year starting from the day the login was made.

**Comment by nicholasg97** [comment]
Appreciate it!
