### ISSUE TITLE
Incorrect Login Credentials?

### ISSUE THREAD

**Issue by loadingalias** [Rishikant181/Rettiwt-API#366]
Hey, I've been trying to generate my credentials... but for whatever reason am getting the following:

Error: Incorrect password given for the given Twitter account

It's 100% the right login information. Ideas?

**Comment by Rishikant181** [comment]
Did you follow [these](https://rishikant181.github.io/Rettiwt-Auth/#md:cli-usage) steps for logging in?

If yes, did you make sure that the supplied parameter order is email, username then the password?

If the parameter order is correct, did you check your email if any OTP has been sent by Twitter/X in order to verify your account?

**Comment by loadingalias** [comment]
I did follow the steps. The first time I followed it to the letter; the second time I kind of just worked with it myself.

For whatever reason, I'm unable to get my credentials issued. No OTP was sent. It's honestly driving me mad. The format is email, username, and password.

I don't understand it. I deploy Flask apps all the time - no issue. I connect to Twitter with my own personal tools built for Twitter's new API. I deploy ML models; and evaluate them with no issues. AuthO is never an issue. I just can't even come up with an idea as to how to fix it. 

I was wondering if you've successfully logged in to an X/Twitter account that had a valid phone number connected using your process. What about accounts with no number and just the email? 

Any ideas? Thanks for replying, man. You're doing God's work here. Haha

**Comment by Rishikant181** [comment]
While logging in to Twitter Web app, do it ever ask you to confirm you phone number?

**Comment by loadingalias** [comment]
Never. I've never had to confirm anything like that - phone, email, etc. I just login - sometimes using SSO and others with the normal user/pass combo. 

It's frustrating because I've written a really fucking cool tool, but I can't afford to spend $5,000 to test through the API. Your option is like my last. Haha. I appreciate the one on one; please, let me know if you have any ideas. Thanks again, mate.

**Comment by Rishikant181** [comment]
To check, immediately after an unsuccessful attempt of logging in via rettiwt-auth, try logging in to Twitter from your browser's incognito mode, and see if you were asked for something other than email and password.
