### ISSUE TITLE
Is it possible to join the user timeline?

### ISSUE THREAD

**Issue by the-content** [Rishikant181/Rettiwt-API#367]
I need to get the user's timeline and filter it by different types, such as tweets, retweets, likes or replies, and then paginate through the cursor

**Comment by Rishikant181** [comment]
Although this is possible, it is not implemented in this package as of now. I'll try to add it in the next feature update.

Thanks for the feedback!

**Comment by Rishikant181** [comment]
I have opened up a separate issue #368  regarding implementation of this feature. Any further discussions regarding this feature will be done there.

**Comment by omarcinkonis** [comment]
@0xAddress I have added the endpoint for user tweets. If you need it right now, you can use my fork: https://github.com/omarcinkonis/Rettiwt-API

Usage: rettiwt.user.tweets(userId)

**Comment by Rishikant181** [comment]
@0xAddress The feature has been added in the dev branch, but will be published with the next feature update. Thanks for your feedback!

**Comment by Rishikant181** [comment]
@0xAddress Rettiwt-API v2.2.0 having this feature, has been released!

**Comment by the-content** [comment]
thank you very much for your efforts
