### ISSUE TITLE
Implement fetching of user timeline

### ISSUE THREAD

**Issue by Rishikant181** [Rishikant181/Rettiwt-API#368]

**Comment by omarcinkonis** [comment]
I have opened a PR to rettiwt-core, if you approve it, I will open a PR here to add user tweets endpoint.

https://github.com/Rishikant181/Rettiwt-Core/pull/74

**Comment by Rishikant181** [comment]
@omarcinkonis I have approved the PR and the changes have been merged and published as an alpha pre-release.

Please use rettiwt-core@3.2.0-alpha.0 (latest alpha) for development purpose for now.

After a few more feature additions, we'll migrate from rettiwt-core alpha to stable upon next Rettiwt-API release. Thanks for the contributions!
