### ISSUE TITLE
Add proxy management

### ISSUE THREAD

**Issue by omarcinkonis** [Rishikant181/Rettiwt-API#369]
Twitter API has a limit:
500 requests / 10 minutes / 1 IP

With more IPs, higher limit can be achieved. Internal proxy management would be beneficial for this.

I suggest adding proxy config parameter to Rettiwt constructor. The config should be passed and applied in FetcherService request() method.

**Comment by Rishikant181** [comment]
I'll be looking into it now.

**Comment by Rishikant181** [comment]
Won't rotating the proxies with successive requests flag the Twitter account with suspicious activity? Because on Twitter's side, they might see activity from the same account, although from different IPs.

**Comment by omarcinkonis** [comment]
Rettiwt constructor already takes apiKey as a parameter. Accounts can have proxies assigned to them. As long as proxy is kept consistent for each account, this is not going to be a problem.

**Comment by Rishikant181** [comment]
So one apiKey must have one proxy?

**Comment by Rishikant181** [comment]
Got it
