### ISSUE TITLE
Possible to search for tweets only?

### ISSUE THREAD

**Issue by Coareal** [Rishikant181/Rettiwt-API#371]
Using tweet.search(user) returns tweets including replies

Is it possible to filter for only the main tweets? Those that appear on the timeline

**Comment by Rishikant181** [comment]
Although it's possible, but it has not been implemented in this package as of now. It's a minor addition that will be surely added in the next feature update (hopefully coming Monday).

**Comment by Rishikant181** [comment]
For now, for filtering out replies, you may iterate over the returned list and pick up only those tweets whose 'replyTo' field is null/undefined. Such tweets are the original tweets and not replies.

This is a workaround. Expect the update on Monday.

Thanks for the feedback!

**Comment by Rishikant181** [comment]
@Coareal The feature has been added and after some testing, will be published on Monday.

**Comment by Rishikant181** [comment]
@Coareal Rettiwt-API v2.2.0 having this feature, has been released!
