### ISSUE TITLE
Implement RettiwtFactory

### ISSUE THREAD

**Issue by omarcinkonis** [Rishikant181/Rettiwt-API#374]
A factory class may be added to create new Rettiwt with rotating config.

Rate limit is currently 500 requests / 10 minutes / 1 ip. Rotating config will extend this limit.

Config for the factory could look something like this:
```
[
  {
    "twitterApiKey": "exampleWithProxy1",
    "proxyConfig": {
      "proxyHostname": "host1",
      "proxyPort": "3000",
      "proxyUsername": "user1",
      "proxyPassword": "pass1"
    }
  },
  {
    "twitterApiKey": "exampleWithProxy2",
    "proxyConfig": {
      "proxyHostname": "host2",
      "proxyPort": "3000",
      "proxyUsername": "user2",
      "proxyPassword": "pass2"
    }
  }
]
```

It might not be necessary to rotate the api key. Currently, the account rate limit is unknown. There are no known cases of blocked accounts due to rotating ip.

In the factory, a couple of strategies can be applied to create Rettiwt:
1. Store last used config index in Redis (cache). Users should provide their Redis details
2. If the user does not provide Redis details, take random config.

Randomness may lead to the same config being used over and over again, resulting in exceeded rate limit for the config. Errors may start appearing before all configs have their rate limits exceeded.

Cached index would ensure configs are used one after another. Errors would only appear if rate limit has been exceeded for all configs.

**Comment by Rishikant181** [comment]
I have a question though. Is it okay if we leave the job of rotating the proxy to the user? That way, they will have the freedom of choosing their rotation strategy. All this library will do is work with the given proxy.

**Comment by omarcinkonis** [comment]
> Is it okay if we leave the job of rotating the proxy to the user?

Whether you want to include this feature is for you to decide. I think it might be useful for many users. The package could be easier to use.

I raised this issue because you left a question here: https://github.com/Rishikant181/Rettiwt-API/pull/372#issuecomment-1729879153

> I was wondering if instead of taking a single proxyUrl, we might use a list of them to implement a rotating proxy. What do you think?

If you want to implement rotating proxy, then this may be a solution. If it is not needed, the issue may be closed.

**Comment by Rishikant181** [comment]
It was implemented at one point, long before this package was made public. And then I scraped it off to relieve the package of any functionalities, that can be added by the users themselves.

Upon some thought, I think it will be better to leave the rotation to the user as it's implementation is trivial. The package provides an option to use proxy and the rotation be left to user.

**Comment by Rishikant181** [comment]
Have you, by any chance, already started working on it?

**Comment by omarcinkonis** [comment]
A little bit, but I haven't done much

**Comment by Rishikant181** [comment]
Let's put it aside for now, since this can be implemented by the user by instantiating different Rettiwt instances with different proxies and rotating through them according to whichever strategy they decide.
