### ISSUE TITLE
Search not working for twitter username that starts with numbers

### ISSUE THREAD

**Issue by Coareal** [Rishikant181/Rettiwt-API#377]
For instance, trying to search for the user 13AK3D or 0Putinyt gives VALIDATION_ERROR

**Comment by Rishikant181** [comment]
That's strange. It should be working find.

Please catch the error and log it to console. See what it says. There might be some other validation error. If possible, please post the error message and the code to reproduce the issue.

Note: While searching for tweets, usernames must be passed as a list of usernames and not as a single string.

**Comment by Coareal** [comment]
Not for tweets, but for details of a user

Try reproducing it with

rettiwt.user.details("13AK3D")

**Comment by Rishikant181** [comment]
Patch incoming. It was a minor problem with the way alphanumeric usernames were validated.

**Comment by Rishikant181** [comment]
@Coareal Please update to latest version (v2.2.1). The issue has been patched.
