### ISSUE TITLE
Adding count parameter doesn't change output

### ISSUE THREAD

**Issue by lukejaw** [Rishikant181/Rettiwt-API#381]
Hi, I have the following code
`await rettiwt.user
  .timeline("44196397", 1)` and it still outputs more than 1 tweet on the timeline? Am I using the count parameter incorrectly? I've tried it on the following as well and it doesn't make a difference

**Comment by Rishikant181** [comment]
It's a known issue that has more to do on Twitter side of things.

When you do not use a cursor (that is, it's the first batch of data being fetched), Twitter just ignores the count and fetches a pre-defined amount of data.

When fetching subsequent batches using a cursor, the count parameter works as usual.
