### ISSUE TITLE
Tweet/timeline search for a specific user not working

### ISSUE THREAD

**Issue by Coareal** [Rishikant181/Rettiwt-API#382]
When using the api to tweet.search or user.timeline (using the corresponding id) the user "puntium", no tweets or timeline are returned, even though going to the user's twitter profile, we can see that it is an active user.

**Comment by Rishikant181** [comment]
I am trying to find out what's wrong, but I think it has something to do with user privacy setting. I'll get back once I identify the problem and a possible fix.

**Comment by Rishikant181** [comment]
@Coareal What is the corresponding id of the user "puntium" which you are using?

**Comment by Rishikant181** [comment]
@Coareal At first, I managed to reproduce the issue, but then I noticed it was just a typo and I was using "2268617852" as user Id (incorrect) instead of "68617852". Using the correct Id, I was able to get the timeline.

**Comment by Coareal** [comment]
Hmm weird that i reran the same code today and is working. 

Will report again if i encounter something similar

**Comment by Rishikant181** [comment]
Sounds good. I'll be keeping this issue open for two weeks. If all seems good by then, it will be closed.

Thanks for the feedback! Means a lot!
