### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by gingerjx** [Rishikant181/Rettiwt-API#384]
Using the same credentials `rettiwt-api` throws `AxiosError: Request failed with status code 429` and I have to wait some time to be able to make the calls again. What are the rate limits?

**Comment by Rishikant181** [comment]
The rate limits are something that I have never personally tinkered with although according to @omarcinkonis, it's 500 requests / 10 minutes / 1 IP. [Link to comment](https://github.com/Rishikant181/Rettiwt-API/issues/369#issue-1906269383)

**Comment by gingerjx** [comment]
Thanks for info!
