### ISSUE TITLE
Add endpoint for user replies

### ISSUE THREAD

**Issue by omarcinkonis** [Rishikant181/Rettiwt-API#387]
User replies to other users' posts are not displayed in timeline. There's a separate endpoint for replies. Add this endpoint. Rettiwt-Core will need to be modified first.

**Comment by Rishikant181** [comment]
@omarcinkonis  https://github.com/Rishikant181/Rettiwt-Core/pull/88#issuecomment-1753156144

**Comment by omarcinkonis** [comment]
Tweet search is a good workaround, the only drawback is that it takes username instead of user id. Personally, I think that storing both username and id, having to access data by different identifiers is a bit inconvenient.

You mentioned:
>Further, there is an irregularity while fetching data from this endpoint, which I have not been able to fix for quite some time.

What is the irregularity?

**Comment by Rishikant181** [comment]
So the irregularity is that in the incoming raw response, the user's tweets and replies as well as the other tweets in the same thread/conversation are mixed, in a nested manner, with each thread having a cursor of it's own. In all other endpoints, the response has been a simple list but in this case, it's a nested list.

(I apologise for the late reply, final year of Uni sucks)

**Comment by Rishikant181** [comment]
@omarcinkonis User replies have been added, will be coming in the next release (v2.3.0) scheduled for Monday.

**Comment by Rishikant181** [comment]
@omarcinkonis Changes have been added in latest release (v2.3.0)
