### ISSUE TITLE
Getting tweet details using guest_token

### ISSUE THREAD

**Issue by zk118** [Rishikant181/Rettiwt-API#388]
Hi, is it possible to male a simple call to get tweet detail (https://twitter.com/elonmusk/status/1711408433042268262) using only the getGuestCredential() ? If yes, what should I pass to the Rettiwt instance ?

I tried using getUserCredential() with cookies but we are limited to 50 calls every X minutes. I want to bypass this by using Proxies.
I recall your we had this ability in previous versions.

Thanks in advance.

**Comment by Rishikant181** [comment]
> I recall your we had this ability in previous versions.

Yes indeed, but when Twitter changed its policies regarding not being able to view anything without logging in, this functionality ceased to work.

However, recently, some parts of Twitter now no longer require logging in and some data can be fetched using guest token. This will surely be added in the next feature update.

I'll be keeping this issue open and active.

**Comment by zk118** [comment]
Thanks, will be following this!

**Comment by Rishikant181** [comment]
@zk118 Changes have been merged and will arrive in the next release.

**Comment by zk118** [comment]
Thanks!

**Comment by Rishikant181** [comment]
@zk118 Please update to v2.3.0
