### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by gingerjx** [Rishikant181/Rettiwt-API#389]
Do you plan to create the same rettiwt-api library but for Python?

**Comment by Rishikant181** [comment]
I have thought about creating a similar library for python, but I fear I can't find the time to do it right now (final year of Uni).

It's not impossible though, and I'll be happy if someone is able to share the labour :)

**Comment by gingerjx** [comment]
Yeah, I fully understand that. Anyway, it's a great project, I hope you find more collaborators!

**Comment by Rishikant181** [comment]
@gingerjx [This](https://github.com/trevorhobenshield/twitter-api-client) might be something that you are looking for.

**Comment by gingerjx** [comment]
Indeed it is what I am looking for, thanks for the help!!
