### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by quan612** [Rishikant181/Rettiwt-API#395]
Hi,

Thanks for the tool, just wondering if:
+ Any rate limit on the usage when we use it
+ Will the cookie be expired once we authenticated? Can we use save the same cookie as env and re-use for subsequent fetch?

**Comment by Rishikant181** [comment]
1. Yes, the package is subject to the same rate limits as the standard rate limits of the Twitter client application (which is still significantly higher than the official Twitter Developer API).
2. The cookie has a validity of a year from the day of authentication and yes, you are supposed to use the same cookie for subsequent fetch. Never generate new cookie for every subsequent request. Generate once and use for a year.

**Comment by Rishikant181** [comment]
Keeping this issue pinned since I failed to mention anything regarding validity of cookies in the docs (dumb me :P)

I'll be updating the docs later.

**Comment by quan612** [comment]
Thanks for your response.

May I know if the limit remaining or limit reset is returned somewhere so we can tell ahead that rate limit is gonna happening.

**Comment by Rishikant181** [comment]
Unfortunately, no such time limit is returned. The only solution which might mitigate hitting the rate limits is introduction and artificial delay in between successive requests.
