### ISSUE TITLE
Count on timeline or replies dosen't work

### ISSUE THREAD

**Issue by Hrodvitnir-Fenrir** [Rishikant181/Rettiwt-API#398]
I have done something like that :

```js
rettiwt.user.timeline("120118721", 5).then(timeline => {
	console.log(timeline.list.length);
}).catch(err => {
	console.log(err);
});
```

But that return me 20 tweet in the list, when a account have pinned tweet that return 23,
Thats not a big issue, just a feature that dosen't work

Sorry for my bad english

**Comment by Rishikant181** [comment]
Are you perhaps using it without logging in?

**Comment by Hrodvitnir-Fenrir** [comment]
Yeah i have a `const rettiwt = new Rettiwt({ apiKey: xxx });` just before

But my bad i don't have seen this closed this issue : https://github.com/Rishikant181/Rettiwt-API/issues/381

**Comment by Hrodvitnir-Fenrir** [comment]
Oh and another ask, sorry if i not verry in the good ticket but, so there is no way to know if a tweet is pinned when we do a `rettiwt.user.timeline()` ?

Or for this we need absolutly to before get `rettiwt.user.details()` for get the pinned and filter it when we get the timeline ? and so make 2 requests ?

**Comment by Rishikant181** [comment]
>But my bad i don't have seen this closed this issue : https://github.com/Rishikant181/Rettiwt-API/issues/381

Yeah, it is as it is. Without a cursor, you are basically forced to fetch the max 20 tweets. Sucks tbh

**Comment by Rishikant181** [comment]
> Oh and another ask, sorry if i not verry in the good ticket but, so there is no way to know if a tweet is pinned when we do a `rettiwt.user.timeline()` ?

Although it's possible to implement this feature, but it has not been implemented yet, so I fear you might have to check beforehand.

**Comment by Hrodvitnir-Fenrir** [comment]
alright thx a lot !
