### ISSUE TITLE
Unable to get the latest user tweets

### ISSUE THREAD

**Issue by bircher044** [Rishikant181/Rettiwt-API#404]
I think this feature is not working anymore. When im using different sessions i'm still facing the limits after 50 total requests. When i'm trying to get the data without login, i'm receiving not fresh twits, but user "top tweets" or something like that. Is there any way to get sorted tweets when you are using a session without login? 
Thank you everyone for the answers in advice

**Comment by Rishikant181** [comment]
Okay I'll be looking into it shortly.

**Comment by Rishikant181** [comment]
@bircher044 The list returned by the method always has the pinned tweet as the first elements. The latest tweets are contained after that. Currently, I'm still working on trying to remove the pinned tweet from the returned list.

**Comment by bircher044** [comment]
I believe thats something different. Here is the list of elonmusk tweets with and without login into account. I see absolutly random ones when i'm not loggined. And they are not pinned.  
![photo_2023-12-19_17-59-10](https://github.com/Rishikant181/Rettiwt-API/assets/95891690/90ce32f9-4624-4425-953b-ddf90278e98b)
![photo_2023-12-19_17-59-01](https://github.com/Rishikant181/Rettiwt-API/assets/95891690/bd75fbf7-5486-428c-9eb5-c7d330cd5b73)

------
thank you for supporting this project!

**Comment by Rishikant181** [comment]
Okay tried it out. Turns out something changed on Twitter (once again). Now Twitter/X shows the top posts when not logged in.

**Comment by bircher044** [comment]
Ok, thank you!
