### ISSUE TITLE
Add ability to upload media in tweets

### ISSUE THREAD

**Issue by Rishikant181** [Rishikant181/Rettiwt-API#413]

**Comment by yiliang114** [comment]
In other words, there is no api to upload media for generating links to send tweets?

**Comment by Rishikant181** [comment]
The ability to upload media is in the works and the corresponding request configuration has been added to Rettiwt-Core. Changes in Rettiwt-API itself will reflect in the next update (currently in dev). I am working on uploading media right now. Progress can be tracked in [this](https://github.com/Rishikant181/Rettiwt-API/tree/media-tweet) branch.
