### ISSUE TITLE
Add request timeout to RettiwtConfig

### ISSUE THREAD

**Issue by omarcinkonis** [Rishikant181/Rettiwt-API#421]
Twitter API usually returns responses instantly. However, if proxy is used, then custom timeout becomes useful.

**Comment by Rishikant181** [comment]
@omarcinkonis are you willing to work on it or shall I?

**Comment by omarcinkonis** [comment]
I can do it, should have time for this tomorrow.

**Comment by Rishikant181** [comment]
@omarcinkonis Thanks, meanwhile I am experimenting on an alternate authentication which does not require a Twitter account.
