### ISSUE TITLE
Is it possible to get authorized user's bookmark list?

### ISSUE THREAD

**Issue by craigary** [Rishikant181/Rettiwt-API#429]
Hi there~

I would like to use rettiwt to grab all my bookmarks and automatically sync to my Notion database, however currently is not possible to get the authorized user's bookmark list info.

Also, I noticed that I am not able to get the api key if i have 2fa enabled: after run `rettiwt auth login <email> <handle> <password>` with 2fa enabled it doesn't return anything. Maybe ask to input 2fa when needed?

Thank you~

**Comment by Rishikant181** [comment]
> however currently is not possible to get the authorized user's bookmark list info.

Yes, unfortunately. The first thing that was prioritized while implementing this API was extraction of data pertaining to other users. Not that the dust has settled, it might be possible to interact with your own user account in the near future.

> Maybe ask to input 2fa when needed?

2fa has not been implemented yet, however, it is certainly in the works and I'm trying to get my head around implementing it.
