### ISSUE TITLE
cannot create api key with npx rettiwt auth login

### ISSUE THREAD

**Issue by Anermers95** [Rishikant181/Rettiwt-API#432]
after running the command, it returns nothing just a blank line.

**Comment by Rishikant181** [comment]
Did you try logging in with the same account on the Twitter Web App? If you are already logged in, then log out then log in again and then try using rettiwt auth again.

**Comment by Anermers95** [comment]
Hi had to make a new tweeter acc for it to work. Also, do u guys have a feature to retrieve all the replies from a tweet id? thanks!

**Comment by Rishikant181** [comment]
> do u guys have a feature to retrieve all the replies from a tweet id?

About that, fetching replies to a tweet had been quite messy for some time so it hasn't been implemented yet (although it's possible). It's currently in the backlog of features :(

I'll open up an issue and I'll see if it's better now (hopefully).

**Comment by Anermers95** [comment]
hope the feature works because that's one of the features that I really need D: but you guys do awesome work thank you so much!

**Comment by Rishikant181** [comment]
Thanks for the feedback, glad you found this useful!
