### ISSUE TITLE
Add ability to fetch replies to a tweet

### ISSUE THREAD

**Issue by Rishikant181** [Rishikant181/Rettiwt-API#433]

**Comment by leaswapdev** [comment]
Hi @Rishikant181, is this feature supported or any similar API? Sorry if I missed something.

**Comment by Rishikant181** [comment]
Unfortunately, it's not supported as of now. Last time I tried to implement it, it was broken and I wasn't able to figure out how Twitter web app does that.

**Comment by leaswapdev** [comment]
Thank you for your quick response. And, as I see at [issue 444](https://github.com/Rishikant181/Rettiwt-API/issues/444#issuecomment-2106366766), he's mentioning searching by conversation id, but it seems like it doesn't work.

Anyway, thanks for your hard work!
