### ISSUE TITLE
Auth login with Two-Factor Authentication

### ISSUE THREAD

**Issue by Maaster** [Rishikant181/Rettiwt-API#435]
Hello! 

I've been trying to get this to run, but Im either blind or there is no way given to supply the code for a 2FA. The output for the `auth login` command is just blank (even when using `-l` for some reason), so I'm guessing the request goes through and is correct, but its asking for the 2FA code.

And yes, I did try in incognito browser, and it works, after I supply the 2FA code.

Am I just missing something and this is possible or do I need to remove 2FA? (Or need a new account?)

Thanks!

**Comment by Rishikant181** [comment]
Unfortunately, currently there is no support for 2FA :(. But yes, we have plans of implementing it in the next update to the authentication side of things.
