### ISSUE TITLE
tweet.search returning empty tweets list for some users

### ISSUE THREAD

**Issue by Othmanosx** [Rishikant181/Rettiwt-API#436]
when using `tweet.search`, some users return an empty tweets list

example:
```javascript
  const tweets = await rettiwt.tweet.search({
    fromUsers: ["AppFaves"],
  })
```
returns 0 tweets even though the account `@AppFaves` is active and does have tweets, this issue happens with other accounts as well but not all.

**Comment by Rishikant181** [comment]
It's an issue with the search endpoint used to fetch tweets. The same behavior is displayed when trying to search for the tweets in the Twitter Web App:

![Capture](https://github.com/Rishikant181/Rettiwt-API/assets/66668688/d8d5d7d0-d585-4b33-a496-c3641f8134aa)

I'll look into it to do what I can, but given it's an issue with Twitter Web App itself, I don't think much can be done about it.

You may use either the [Rettiwt.user.timeline](https://rishikant181.github.io/Rettiwt-API/classes/UserService.html#timeline) or [Rettiwt.user.replies](https://rishikant181.github.io/Rettiwt-API/classes/UserService.html#replies) to fetch the tweets and replies, as an alternative.
