### ISSUE TITLE
The number of uploaded images should be limited to 4

### ISSUE THREAD

**Issue by yiliang114** [Rishikant181/Rettiwt-API#446]
Otherwise, the upload fails. Although the interface returns true, it is successful, but the actual release is not successful.

<img width="376" alt="image" src="https://github.com/Rishikant181/Rettiwt-API/assets/11473889/e9f8287a-bc6b-4bdf-8786-73e5dab26797">

**Comment by Rishikant181** [comment]
So Twitter allows upto a max of 4 images, is that correct?

**Comment by yiliang114** [comment]
Yes. I also found it only after uploading 5 pictures through the interface. At first, I was very confused. The interface clearly returned true, but it was not released successfully.

![image](https://github.com/Rishikant181/Rettiwt-API/assets/11473889/3a00eb16-0b91-4b0d-a2e3-a44805222e45)

**Comment by Rishikant181** [comment]
Working on a patch right now.

**Comment by yiliang114** [comment]
> Working on a patch right now.

Your efficiency is too high!

**Comment by Rishikant181** [comment]
I'll have to first check what are the limits on each media type (I would have already known this if only I ever used Twitter :P)

**Comment by Rishikant181** [comment]
Patch might take some time since introduction of inferring media types while uploading is required.

In the meantime, it must be noted that at most 4 images or 1 GIF can be uploaded in a single Tweet.
