### ISSUE TITLE
Search API no longer retrieves any tweets if only words are provided

### ISSUE THREAD

**Issue by Jeto143** [Rishikant181/Rettiwt-API#454]
The following code:

```js
rettiwt.tweet.search({
  words: ['hello'],
})
```

retrieves a list of tweets in 2.4.2 but no longer retrieves anything in 2.5.0 (no errors, just an empty list).

It seems like `fromUsers` now needs to be provided for tweets to be retrieved.

Is this intended behavior? I'm sorry if it was mentioned somewhere already.

**Comment by Rishikant181** [comment]
The `words` search parameter has been renamed from `words` to `includeWords` in order to accommodate other word search parameters such as `excludeWords` and `optionalWords`, without any ambiguity #426.

**Comment by Jeto143** [comment]
Oh woops my bad. Wanted to check the docs [here](https://rishikant181.github.io/Rettiwt-API/classes/TweetFilter.html#includeWords), but for some reason it defaults to displaying no fields for me (had to manually check "External" at the top right, now I see them).

Closing this, sorry!
