### ISSUE TITLE
CLI - user timeline error

### ISSUE THREAD

**Issue by capps99** [Rishikant181/Rettiwt-API#455]
I have been experimenting with the CLI API, and never able to make it with the 'user' module. The only one that is working well is the 'user details' one.

rettiwt -l -k [API_KEY] user details MetroCDMX
I tested all the 'tweet' module, and they work well.

So, for the rest of user [operation] I got the same error:
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);

Example:
rettiwt -l -k [API_KEY]= user timeline MetroCDMX  
[Rettiwt-API] [FETCH] [2024-02-11T19:52:59.225Z] {"resourceType":"/i/api/graphql/H8OOoI-5ZE4NxgRr8lfyWg/UserTweets","args":{"id":"MetroCDMX"}}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);

===========================================================================
Update:
After more analysis, I found that it's also failing on the JS implementation:
rettiwt.user.timeline('MetroCDMX')
    .then(details => {
        console.log(details)
    })
    .catch(error => {
        console.error(error);
    });

Response:
DataValidationError {
  name: 'VALIDATION_ERROR',
  message: 'One or more validation errors occured. Check details',
  data: [
    ValidationError {
      target: [FetchArgs],
      value: 'MetroCDMX',
      property: 'id',
      children: [],
      constraints: [Object]
    }
  ]
}

===========================================================================            
            
Environment:
Node version - v20.11.0
npm version - 10.2.4

**Comment by Rishikant181** [comment]
All methods of `user` module (except `user.details`) take in a user id (which is a numeric string) as input, not a username. You can see more about this error by inspecting the `constraints` field of the thrown error.

The error thrown in your case is a ValidationError, which means that the arguments themselves were invalid.

**Comment by capps99** [comment]
Thanks, yes, it worked!! Thank you so much.

Basically, I google:  "Twitter ID for a user" and was able to find it!.

This library it's amazing. Congrats!

**Comment by capps99** [comment]
Worked with numeric ID.

**Comment by Rishikant181** [comment]
> Basically, I google: "Twitter ID for a user" and was able to find it!.

You can also fetch the user ID by using the `user.details` function by passing in the username. The returned response will have the user ID which you can then use to fetch timeline.
