### ISSUE TITLE
Webhooks for notifications

### ISSUE THREAD

**Issue by smaldd14** [Rishikant181/Rettiwt-API#464]
Is there a way to setup a webhook for notifications you have on Twitter?

Like if I turn on notifications for every Elon tweet, could I have a webhook that gets called when that happens?

I'd be happy to discuss options on how to do this

**Comment by Rishikant181** [comment]
I haven't looked into webhooks for notifications, but it seems interesting.

I'll have to look into it some more to determine if it's possible or not.

**Comment by smaldd14** [comment]
@Rishikant181 I wonder if we could use something similar to the way they do filtered streaming here: https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/api-reference/get-tweets-search-stream

https://developer.twitter.com/en/docs/tutorials/listen-for-important-events

**Comment by Rishikant181** [comment]
You might try something like [this](https://github.com/Rishikant181/Rettiwt-API/pull/467), as done by @Jeto143. However, we will need to add functionality to fetch notifications first.

Edit 1: Actually, @smaldd14 I guess the filtered stream as implemented by @Jeto143 might work out for your use case.
