### ISSUE TITLE
Add the option to view a user's subscriptions, highlights, verified status and media.

### ISSUE THREAD

**Issue by MDCYT** [Rishikant181/Rettiwt-API#469]
It would be a good implementation to be able to see the multimedia files uploaded by the user (Twitter's media section) and also to be able to see the users to which the user in question is subscribed.

**Comment by Rishikant181** [comment]
Oops, seems like I forgot about media section :P. Anyways, it seems easy enough to add. However, the current planned features arriving in the next update (sometime in the next week) have been finalized. Media section might show up in the update after that.

Thanks for the feedback!

**Comment by MDCYT** [comment]
It would also be good to find a way to show if the user is verified or not and if he/she is a verified user, organization or governmental (if possible) and also his/her highlights if he/she has any.

![](https://t.mdcdev.me/vpgxgsf3) ![](https://t.mdcdev.me/sh8p6yc0)

**Comment by Rishikant181** [comment]
Verfied status -> Fixed #487
User highlights -> Resolved #488
User media -> Resolved #489
User subscriptions -> Resolved #490
