### ISSUE TITLE
Ability to "efficiently" quote tweet

### ISSUE THREAD

**Issue by Jeto143** [Rishikant181/Rettiwt-API#470]
At the moment, it's possible to quote tweet by appending a tweet's URL at the end of the tweet's body. However, this URL counts toward the tweet's length and therefore makes it impossible to write quote tweets exceeding ~235 chars (using a short URL such as `https://x.com/_/status/<tweetId>`).

It would be nice to be able to use something akin to `attachment_url` in the documentation link below:
https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-update

I may have missed another way to quote tweet, though!

**Comment by Rishikant181** [comment]
I'll have to dig in to Rettiwt-Core to check if there exists some variable which might be able to help us do this. I'll get back if I find something.

**Comment by Rishikant181** [comment]
@Jeto143 Yes it's possible using an optional field called `attachment_url` in the payload while creating a tweet. I'm working on implementing it.

**Comment by Jeto143** [comment]
> @Jeto143 Yes it's possible using an optional field called `attachment_url` in the payload while creating a tweet. I'm working on implementing it.

Sounds great! My app needs to quote tweet quite a bit so this will help a bunch.
