### ISSUE TITLE
tweet.details(tweetId) does not give back all of tweet

### ISSUE THREAD

**Issue by smaldd14** [Rishikant181/Rettiwt-API#471]
Is there a way to get the entire text of a long form tweet?

Using 
```
rettiwt.tweet.details(tweetId);
```

Only gives back what is visible on the initial "card" of the tweet. For example,

```
rettiwt.tweet.details("1761553546443468848");
```

the `fullText` is "How I Write Viral Posts. I posted daily until November, and stats were average. One morning everything changed, my post went viral everywhere. An Experiment that led to 10 million views on X, Linkedn, Reddit, FB, HackerNews. This is what I did ↓.1. The anatomy of viral…."

But, the actual tweet is much longer.

Is there a way to expand the fullText that is given back?

Link to tweet for reference: https://twitter.com/johnrushx/status/1761553546443468848

**Comment by Rishikant181** [comment]
Found the culprit. Patch is on the way.

**Comment by Rishikant181** [comment]
@smaldd14 The issue has been fixed. Please update to v2.5.3

**Comment by smaldd14** [comment]
Thanks for the quick action, @Rishikant181 !!!
