### ISSUE TITLE
Get tweet URL

### ISSUE THREAD

**Issue by Skydraw** [Rishikant181/Rettiwt-API#473]
HI,

I would like to know if it possible to get tweet URL in the fonction tweet.search ?

I found anything in **src/models/data/Tweet.ts** so it may be not implemented in the futur ?

Thanks you and have a nice day !

**Comment by Rishikant181** [comment]
Tweet URL is not a field that is found in the raw data that is received from Twitter. However, the tweet url follows the syntax:
`https://x.com/<username>/status/<tweet_id>`

The username and tweet id can be found from the details of the received tweet(s).

**Comment by MDCYT** [comment]
Or you can simply replace the username with an "i" (`https://twitter.com/i/status/{id}` or `https://x.com/i/status/{id}`) or any other username, Twitter/X ends up redirecting you to the correct tweet regardless if you put the correct username. 

Example: https://twitter.com/i/status/20 or https://x.com/i/status/20

**Comment by Skydraw** [comment]
Hi ! THank you for your answers guys !
 I finaly took this way !
