### ISSUE TITLE
One or more validation errors occured. Check details

### ISSUE THREAD

**Issue by xue160709** [Rishikant181/Rettiwt-API#480]
Thank you for your open source project! Currently I am encountering a problem during use
```
const url = new URL("http://127.0.0.1:7890")
            const rettiwt = new Rettiwt({proxyUrl:url, logging: true});
            rettiwt.user.timeline("elonmusk").then(
                res => {
                    console.log(res);
                }
            ).catch(err => {
                console.log(err);
            })
```
![image](https://github.com/Rishikant181/Rettiwt-API/assets/5611511/7ebb7dad-9006-40f0-acc3-a341ea2a5b67)

The error message is like this, how should I solve it? Or is this a bug?

**Comment by Rishikant181** [comment]
When fetching timeline, you give the id of the user as a parameter, not the username (the same is shown in the error details: `id must be a number string')

To get the id, fetch the details of the user first using `user.details` method. Then use the id from the details to fetch timeline.

**Comment by xue160709** [comment]
> When fetching timeline, you give the id of the user as a parameter, not the username (the same is shown in the error details: `id must be a number string')获取时间线时，您将用户的 id 作为参数提供，而不是用户名（错误详细信息中显示的内容相同：“id 必须是数字字符串”）
> 
> To get the id, fetch the details of the user first using `user.details` method. Then use the id from the details to fetch timeline.要获取 id，请首先使用 `user.details` 方法获取用户的详细信息。然后使用详细信息中的 id 来获取时间线。

Perfect solution! Thank you for your help, have a good day!
