### ISSUE TITLE
Option to execute actions to Tweets from Tweet object

### ISSUE THREAD

**Issue by MDCYT** [Rishikant181/Rettiwt-API#481]
It would be nice that within the object of the tweets you can execute options to these same tweets to make it faster, for example `tweet.favorite(`), `tweet.retweet()`, `tweet.reply("Content", ["./image.png"])`

**Comment by Rishikant181** [comment]
Implementing ability to execute actions will require passing in a rettiwt instance to Tweet object, which would then lead to a change in the structure of the project. 

Currently, the project targets a "separation of concerns" based structure, in which the Tweet class' only concern is deserialization of the raw tweet data into a simpler form. Adding actions will require the Tweet class to implement async functions which will utilize the rettiwt instance to make requests to Twitter, which will be contrary to the intended structure.

Sure, adding actions will be more convenient, but, the difference it makes is too small for changing the structure.
