### ISSUE TITLE
Is it possible to tweet with media by using binary data?

### ISSUE THREAD

**Issue by AlejandroAkbal** [Rishikant181/Rettiwt-API#482]
This way I don't have to save media to disk just to use with this FANTASTIC library

I could just HTTP get the media and pipe it in binary data

Love your work <3

**Comment by Rishikant181** [comment]
This has been implement in [Rettiwt-Core](https://github.com/Rishikant181/Rettiwt-Core/pull/133) and changes will reflect in Rettiwt-API in the next feature update. 

Thanks for the feedback!

**Comment by AlejandroAkbal** [comment]
Damn that's fast, thank you 💜
