### ISSUE TITLE
Switching Twitter Account Automatically

### ISSUE THREAD

**Issue by yulonghe97** [Rishikant181/Rettiwt-API#483]
Let's say we are going to scrape a large amount of data repeatedly. Using one Twitter account shouldn't be reliable and may get banned when it's detected. 

Is there a possibility of switching between a list of accounts (generated API key) to minimize the risk? For example, the project https://github.com/vladkens/twscrape has a feature of automatic account switching which is quite helpful.

Look forward to getting some suggestions and insights on this. Really nice work here 👍 .

**Comment by Rishikant181** [comment]
For now, no such feature is provided and this is done by the consumer of the library and not the library itself.

I'm still working out a way to implement this efficiently.

**Comment by yulonghe97** [comment]
Thanks Rishikant!
