### ISSUE TITLE
Is there a rate limit?

### ISSUE THREAD

**Issue by JunyiChE** [Rishikant181/Rettiwt-API#495]
Hi,
very impressive work and I appreciate your contribution.

However, in reddit, you said there is no rate limit, which I encounter when use the get tweet detail method as a guest. It will report too many HTTP request after extracting about 100 tweets. 

If there is a rate limit, what is it per miniute. And if I encounter that, how long should I wait?

**Comment by JunyiChE** [comment]
it will actually report this and I appreciate your possible response [RettiwtError: TOO_MANY_REQUESTS
    at HttpError.RettiwtError [as constructor] (F:\ChatAPI\node_modules\rettiwt-api\dist\models\errors\RettiwtError.js:27:28)
    at new HttpError (F:\ChatAPI\node_modules\rettiwt-api\dist\models\errors\HttpError.js:35:28)
    at exports.ErrorService.ErrorService.createHttpError (F:\ChatAPI\node_modules\rettiwt-api\dist\services\internal\ErrorService.js:94:16)
    at exports.ErrorService.ErrorService.handleHttpError (F:\ChatAPI\node_modules\rettiwt-api\dist\services\internal\ErrorService.js:72:20)
    at exports.ErrorService.ErrorService.handle (F:\ChatAPI\node_modules\rettiwt-api\dist\services\internal\ErrorService.js:39:14)
    at F:\ChatAPI\node_modules\rettiwt-api\dist\services\internal\FetcherService.js:187:52
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 429
}
]

**Comment by JunyiChE** [comment]
Actually, it will always fail to retrieve a certain tweet in my dataset after starting the process, but the tweet actually exist.  I can manually retrieve this tweet with id when I shut down the program and reboost it.  But in the same program, if I do not stop, even I wait several minutes, it will report too many requests.

By the way, I am using proxy.  Any ideas for this?

**Comment by Rishikant181** [comment]
> However, in reddit, you said there is no rate limit, which I encounter when use the get tweet detail method as a guest. It will report too many HTTP request after extracting about 100 tweets.

Yeah the rate limits you face are the standard rate limits you face whenver you visit any website on a browser, which are in place to prevent heavy load.

> If there is a rate limit, what is it per miniute. And if I encounter that, how long should I wait?

Personally, I never tested it fully, and it mostly depends on your network bandwidth.

> But in the same program, if I do not stop, even I wait several minutes, it will report too many requests.

A solution will be to introduce an artificial delay between subsequent calls to Rettiwt-API.

**Comment by JunyiChE** [comment]
> > However, in reddit, you said there is no rate limit, which I encounter when use the get tweet detail method as a guest. It will report too many HTTP request after extracting about 100 tweets.
> 
> Yeah the rate limits you face are the standard rate limits you face whenver you visit any website on a browser, which are in place to prevent heavy load.
> 
> > If there is a rate limit, what is it per miniute. And if I encounter that, how long should I wait?
> 
> Personally, I never tested it fully, and it mostly depends on your network bandwidth.
> 
> > But in the same program, if I do not stop, even I wait several minutes, it will report too many requests.
> 
> A solution will be to introduce an artificial delay between subsequent calls to Rettiwt-API.

Thanks for responding and I find a very efficient solution.  I am using proxy (do not know whether the ip address of mine will change everytime I boost the program), and when I reboost the program, it will be all fine, with no rate limit error, but after a period, it will happen.

Therefore, the most efficient way to tackle this is to store the data where you have processed so far, and next time, move directly to the data you have unprocessed.

By introducing a global management tool to reboost the program multiple and endless times when you explictly stop it, it can fetch the data very quickly without any rate limit. Think this an efficient way.

**Comment by JunyiChE** [comment]
Of course, you will need to automatically kill the program and reboot it when you face the rate limit error.

**Comment by Rishikant181** [comment]
Thanks for the feedback, I might as well develop a plugin that accomplishes this task :P

**Comment by 14cnewman** [comment]
Hi! I was wondering if we do get the TOO_MANY_REQUESTS error if there is anything I can do to fix it? I've tried cutting down the requests to a 100 tweets but I am still getting that error. I am wondering if I need to wait a certain amount of time after accidently submitting too many requests till I will again be able to run the script?

**Comment by Rishikant181** [comment]
@14cnewman When an Error 429 is thrown, the error does contain a 'retry after' field which specifies the amount of time you must wait before making another request. You can use a custom error handler which retrieves that field's value and wait for specified time before trying again.

**Comment by 14cnewman** [comment]
Okay!! Thank you so much!!
