### ISSUE TITLE
user.followers('id', count) seems to not be functional.

### ISSUE THREAD

**Issue by MsVoxxie** [Rishikant181/Rettiwt-API#499]
Using the optional count paramater seems to be completely ignored and its fetching 100(?) followers, Im looking to only nab 5.

**Comment by Rishikant181** [comment]
That's just one quirk of a reverse engineered solution. When you fetch the followers for the first time (without using any cursor), it fetches 100 by default (overriding the count). For successive batches using the returned cursor, you can set an arbitrary count and it will not be overridden. That's the way it is, unfortunately.

**Comment by MsVoxxie** [comment]
Ahh, I apologize for the false report, then. Thanks for clearing that up :)
