### ISSUE TITLE
rettiwt.user.timeline(id, 5) returns the entire payload instead of just 5 tweets

### ISSUE THREAD

**Issue by randyyu13** [Rishikant181/Rettiwt-API#502]
Issue is what title says ^

**Comment by Rishikant181** [comment]
All cursored resources (like timeline, search, likes, retweets, followers, followings, etc) have a quirk, where if you fetch the first batch (without using a cursor), the default count of 20 items are fetched and the count is ignored. It's just how Twitter client's API works. For successive batches however, the cursor is taken into account.

TL;DR: Count parameter doesn't work for the first batch of tweets, but works for successive batches.

**Comment by Rishikant181** [comment]
Another thing to add, if you are using it without logging in, count won't work even with a cursor and you'll just get the most popular tweets and not the recent ones (this too is a limitation).

**Comment by randyyu13** [comment]
Got it
