### ISSUE TITLE
When setting api key in .env, client is in guest auth mode

### ISSUE THREAD

**Issue by randyyu13** [Rishikant181/Rettiwt-API#504]
I tried moving my api key from a test script to a .env file and loading it with env.TWITTER_KEY and when I run user.timeline it returns what the timeline would look like from a guest user instead of an authenticated user. Any ideas on how to properly do this?

**Comment by randyyu13** [comment]
Actually I mightve forgotten something let me double check lol sorry

**Comment by randyyu13** [comment]
Nope I double checked, still same issue. Any ideas?

**Comment by randyyu13** [comment]
My setup:
script.js:

const apiKey = process.env.TWITTER_KEY;
const rettiwt = new Rettiwt({ apiKey });

**Comment by randyyu13** [comment]
.env:

TWITTER_KEY='api key'

**Comment by Rishikant181** [comment]
The correct syntax is:

```
const twitterKey = process.env.TWITTER_KEY;
const rettiwt = new Rettiwt({ apiKey: twitterKey })
```
