### ISSUE TITLE
Is there a way to extract the top following of a user?

### ISSUE THREAD

**Issue by JunyiChE** [Rishikant181/Rettiwt-API#505]
Hi,

Again, I wanna ask if there's a way to extract the top followings of a user? As current implementation can only extract the following from batch to batch (cursor). If I understand right, move to the next cursor will also count as a request? which will easily lead to rate limit error even for extracting a single user.

So, is there a way to only extract the top 100 followings with the highest followers? Or do we have a better way to tackle the rate limit issue. Since the user.following feature requires a log in, the shutdown and reboot strategy seems not to work anymore, as the identification is through the user account? not the IP address.

**Comment by Rishikant181** [comment]
Nope, the Twitter Web App API does not provide any way to sort the followings and the order in which they are fetched cannot be changed, unfortunately :(
