### ISSUE TITLE
Extracting timeline of For You and Following

### ISSUE THREAD

**Issue by Sylixa** [Rishikant181/Rettiwt-API#508]
Hi,
I wanna ask if extracting For You and Following timeline possible??
I could only find user.timeline which return user timeline but not the other two

Thanks

**Comment by Rishikant181** [comment]
Unfortunately both are currently not possible (and you just gave me the idea to implement it in the near future :P)

I'll see if it's possible and if yes, I'll be implementing it in the next major update that will be releasing shortly and is being worked on.

Thanks for the feedback!

**Comment by Sylixa** [comment]
Ah ok, i really hope to see it in the next release

Good luck on the major update

Thanks you for the quick reply and the amazing library

**Comment by spencer17x** [comment]
I really need this, too,Is there any progress?

**Comment by Rishikant181** [comment]
It's currently being tested in rettiwt-core. If it works fine there, I'll notify here.

**Comment by spencer17x** [comment]
great!!!

**Comment by Rishikant181** [comment]
Fixed #559
Fixed #560
