### ISSUE TITLE
Regarding rollout of updates and addressing of issues

### ISSUE THREAD

**Issue by Rishikant181** [Rishikant181/Rettiwt-API#509]
As some of you might know, I am currently in my final semester of my Bachelors in Technology and as a result, have been quite busy (a lot, actually) on my final year Major Project, which is due in exactly a month from now. As a result, updates to Rettiwt-API have been quite slow, and the commits being pushed to the repo have mostly been under-the-hood changes to the internal architecture of the library.

All the issues will be addressed eventually, once I've dealt with my Major Project. I thank you for you feedback and patience.

**Comment by AlejandroAkbal** [comment]
Thank you for your great work, if there is any way to send you a donation please let me know

**Comment by Rishikant181** [comment]
Sadly, I've not setup any means for donations as of now.

Rest assured, even without donations, I'll be willingly working on this project. 

Regardless, thanks for asking, it means a lot.

**Comment by kaf-lamed-beyt** [comment]
I think you can try setting up a GitHub sponsors account @Rishikant181

**Comment by Rishikant181** [comment]
Definitely checking it out. Thanks for the heads up!

**Comment by Rishikant181** [comment]
Okay  so my Major Project presentation will be over by this weekend. Expect updates to rollout next week!

**Comment by kaf-lamed-beyt** [comment]
Looking forward to it @Rishikant181!

**Comment by Rishikant181** [comment]
Project done now back to code!
