### ISSUE TITLE
A lot of questions with my tests

### ISSUE THREAD

**Issue by Nevgup** [Rishikant181/Rettiwt-API#517]
Hello

Is it possible to contact you like on Discord for example please ?
I really need some help with accounts and the code verification/proxies etc etc....

Ofc when you have time

Thanks !

**Comment by Nevgup** [comment]
nikos5986 if you dont want to give your tag in public

**Comment by Rishikant181** [comment]
@Nevgup Altough I use discord quite often, but I would prefer to keep discussions regarding this library to this repo only. Don't wanna get things mixed up.

**Comment by Nevgup** [comment]
No problem I understand, thanks

**Comment by Rishikant181** [comment]
@Nevgup You may open up issue regarding question you wanna ask here, so that if someone else has a similar query too, they might find it helpful.
