### ISSUE TITLE
Broken fetching followers/following

### ISSUE THREAD

**Issue by Rishikant181** [Rishikant181/Rettiwt-API#519]
Fetching followers/followings is broken on Twitter's end as of now. All we can do is wait before trying to fix it.

Thanks for your patience!

**Comment by omarcinkonis** [comment]
Seems to be resolved, both endpoints return the same data as before

**Comment by Rishikant181** [comment]
Okay I'll check it again, and if does work as expected, then close is this issue.

**Comment by Rishikant181** [comment]
So followers/following is working now, but it still disregards the `count` parameter.

**Comment by Rishikant181** [comment]
Just checked and although it's working, it still disregards the `count` parameter.
