### ISSUE TITLE
Working accounts

### ISSUE THREAD

**Issue by Nevgup** [Rishikant181/Rettiwt-API#520]
Ok so I wanna scrape Twitter at high frequency (get last tweets of a specific user)
I have proxies and account, and at the beginning it was good, I did can use 90-95% of these accounts after login 

The problem is that now, even with the same proxies, they dont work anymore, maybe 95% of them, maybe 100%

I retook some accounts, with same proxies, and it dont work, even with authProxyUrl etc…

I realllyyyy need a way to get working accounts, and good proxies to get last tweets, even if I have to pay

Thanks for your help

**Comment by Eniamza** [comment]
Hey there, it'd be really helpful if you share some more information, such as Error Logs. It might be that you're hitting some rate limits or your Twitter account was restricted. 

Cheers.

**Comment by Rishikant181** [comment]
@Nevgup I would recommend to create a custom error handler that implements the `IErrorHandler` interface, which would better help you handle errors and diagnose them.

The default error handler is quite generic and all it does is printout a simple error message.

[Here's](https://github.com/Rishikant181/Rettiwt-API/issues/516#issuecomment-2059722112) how you can do so.
