### ISSUE TITLE
Wanting tweets from specific days

### ISSUE THREAD

**Issue by 14cnewman** [Rishikant181/Rettiwt-API#528]
Hi! Apologies if this is somewhere in your notes, but I want to pull tweets from specific days- using the createdAt id maybe? But can't seem to figure out how. Thank you for your help!

**Comment by Rishikant181** [comment]
Yup you can use the `startDate` and `endDate` parameters for filtering while searching for tweets as follows:

```
const rettiwt = new Rettiwt({ apiKey: API_KEY, logging: true });

const tweets = await rettiwt.tweet.search({
    fromUsers: ['user1'],
    startDate: new Date('2024-04-24'),
    endDate: new Date('2024-04-25')
}, 10);
```

The above snippet will fetch tweet from 'user1' from 2024-04-24 to 2024-04-25. For fetching tweets from a single day, you may set the `startDate` and `endDate` to be same.

**Comment by 14cnewman** [comment]
Thank you so much!!! :D
