### ISSUE TITLE
UserService.timeline(id)：Tweets from some users may not be fetched

### ISSUE THREAD

**Issue by Pvvv** [Rishikant181/Rettiwt-API#540]
I used my own Twitter account to repost the following user’s tweets, https://x.com/Yizhimao_super
and I called the UserService.timeline(id) method with my id, The tweet information cannot be obtained through the UserService.timeline(id) method, but User.statusesCount has increased

**Comment by Rishikant181** [comment]
Any specific tweet which raised the issue?

**Comment by Pvvv** [comment]
> Any specific tweet which raised the issue?

https://x.com/Yizhimao_super/status/1792033829420716509

**Comment by Rishikant181** [comment]
Strange, I retweeted the given tweet and then immediately fetched my timeline, and the retweet shows up.

Are you using the library with an api key?

**Comment by Pvvv** [comment]
> Strange, I retweeted the given tweet and then immediately fetched my timeline, and the retweet shows up.
> 
> Are you using the library with an api key?

yes use api key ,
I have reposted this https://x.com/Yizhimao_super/status/1792033829420716509
 my id is "1464844738197168130" and my userName is "kelimacha1",
you can use UserService.timeline(id) method with my id, then you will find the result don't have that tweet

**Comment by Rishikant181** [comment]
It's being returned on your result. In the returned list of tweets, it's the Tweet at index 1. The Tweet at index 0 is always the pinned tweet. Therefore, for users who have a pinned tweet, the 1st list item the pinned tweet, followed by the rest of the timeline tweets. See remarks of [`user.timeline`](https://rishikant181.github.io/Rettiwt-API/classes/UserService.html#timeline) method.

**Comment by Pvvv** [comment]
> It's being returned on your result. In the returned list of tweets, it's the Tweet at index 1. The Tweet at index 0 is always the pinned tweet. Therefore, for users who have a pinned tweet, the 1st list item the pinned tweet, followed by the rest of the timeline tweets. See remarks of [`user.timeline`](https://rishikant181.github.io/Rettiwt-API/classes/UserService.html#timeline) method.

I have reposted this tweet https://x.com/Yizhimao_super/status/1792033829420716509, and the user.timeline method i called, but I didn't find it in the timeline, as shown below
 my tweet is "https://x.com/kelimacha1" and my tweet id is "1464844738197168130" , you can use 
 user.timeline('1464844738197168130')  too, you will find that it does not exist.
Finally, thank you very much for your help
![image](https://github.com/Rishikant181/Rettiwt-API/assets/16501795/fb6f86db-b4e7-41c6-869f-bf5a2d5f669e)

**Comment by Rishikant181** [comment]
![image](https://github.com/Rishikant181/Rettiwt-API/assets/66668688/74e15f56-5227-492f-9b6b-3f79caaa73a9)

I'm getting your retweet as expected, it's location is at index 1 too.

![image](https://github.com/Rishikant181/Rettiwt-API/assets/66668688/701955b2-a5c6-4767-9041-ba9109684997)

**Comment by Pvvv** [comment]
> ![image](https://private-user-images.githubusercontent.com/66668688/333217351-74e15f56-5227-492f-9b6b-3f79caaa73a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODExNDksIm5iZiI6MTcxNjQ4MDg0OSwicGF0aCI6Ii82NjY2ODY4OC8zMzMyMTczNTEtNzRlMTVmNTYtNTIyNy00OTJmLTliNmItM2Y3OWNhYWE3M2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE2MTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNDE5OWJkYjRhN2ZjNjdhZjRlMTdlNDk1YmEzMTUwMjQyZjNhMGVmYjA0YTM3NzFiNWMwMDQ3NzU4ZTM1ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DsasjPAZsht5byo6GxZ8fDMbRAQVOGAd3Nh1Xck8xnU)
> 
> I'm getting your retweet as expected, it's location is at index 1 too.
> 
> ![image](https://private-user-images.githubusercontent.com/66668688/333217826-701955b2-a5c6-4767-9041-ba9109684997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODExNDksIm5iZiI6MTcxNjQ4MDg0OSwicGF0aCI6Ii82NjY2ODY4OC8zMzMyMTc4MjYtNzAxOTU1YjItYTVjNi00NzY3LTkwNDEtYmE5MTA5Njg0OTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE2MTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYzEzYmQzNmYyMTE1YzQ5N2M0YTdlOWRlMzBhZjE4NTQzMzg1NmNlNGE0Y2FiYmM0NDE4YWRkYjY0NDc2YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RUPz9I4RKfOJr4UIK3CmkiS2mSZlwAEWx2X61yLCl9E)

I think it's a problem with my Twitter account. I'll change my account and try again. Thank you very much for your help.
