### ISSUE TITLE
Rettiwt-API unable to upgrade to 3.0.0 using npm tool

### ISSUE THREAD

**Issue by Pvvv** [Rishikant181/Rettiwt-API#541]
command: npm update rettiwt-api
result:  Rettiwt-API can only go to rettiwt-api@2.7.1

**Comment by Rishikant181** [comment]
can you manually change rettiwt-api version in package.json to 3.0.0, then use npm install and see if it helps.

**Comment by Pvvv** [comment]
> can you manually change rettiwt-api version in package.json to 3.0.0, then use npm install and see if it helps.

This works, thank you
