### ISSUE TITLE
Is there an api that allows me to get user notifications to all tweets

### ISSUE THREAD

**Issue by spencer17x** [Rishikant181/Rettiwt-API#542]
Show like https://x.com/i/timeline

**Comment by spencer17x** [comment]
Now that I'm using tweet.search to get some of the user's tweets, how do I get the user's retweets

**Comment by Rishikant181** [comment]
For notification, there is not endpoint yet.

As for retweets, they need to fetched from `user.timeline`, which returns both the original tweets as well as retweets. You will need to filter out the original tweets using the tweetBy field to get the retweets, however.

**Comment by spencer17x** [comment]
That way, it is easy to report too many requests errors if you need to query multiple users

**Comment by Rishikant181** [comment]
Unfortunately, the Twitter Web App provides no such way and since this library is works by reverse-engineering the web-app, it's currently not possible to just fetch the retweets.

**Comment by spencer17x** [comment]
But why should web-based twitter get access to retweets

**Comment by Rishikant181** [comment]
This library is created by reverse-engineering the endpoints used by the Twitter Web-App, and this library can only do what the Twitter Web App can do. The web app currently does not provide any means to search for a user's retweets.

**Comment by Rishikant181** [comment]
Fixed #560 
Fixed #559

**Comment by spencer17x** [comment]
> Fixed #560 Fixed #559

Is there any usage documentation?

**Comment by Rishikant181** [comment]
It's in dev branch right now. Release (v3.1.0) will be on Tuesday (hopefully).

**Comment by spencer17x** [comment]
> It's in dev branch right now. Release (v3.1.0) will be on Tuesday (hopefully).

Any links?

**Comment by Rishikant181** [comment]
You'll have to manually package it from the dev branch by cloning the repo and using `npm pack` command. Then use yarn or npm to install the locally packaged tarball..

Since it's dev branch, it implies there is still testing and documentation work left. Keep that in mind.

**Comment by spencer17x** [comment]
> You'll have to manually package it from the dev branch by cloning the repo and using `npm pack` command. Then use yarn or npm to install the locally packaged tarball..
> 
> Since it's dev branch, it implies there is still testing and documentation work left. Keep that in mind.

I'm referring to the usage documentation

**Comment by Rishikant181** [comment]
Since the package hasn't been released, the documentation haven't been generated yet.

You may, however, refer to the comments in the code itself for the usage:
1. [followed user feed](https://github.com/Rishikant181/Rettiwt-API/blob/013facc97fcaac8ce8bbdca4ebe98f42de369f2d/src/services/public/UserService.ts#L145)
2. [recommended (for you) feed](https://github.com/Rishikant181/Rettiwt-API/blob/013facc97fcaac8ce8bbdca4ebe98f42de369f2d/src/services/public/UserService.ts#L395)
