### ISSUE TITLE
Feature Request: Get creator subscribers

### ISSUE THREAD

**Issue by Timtendo12** [Rishikant181/Rettiwt-API#562]
I dont know if its possible but for this would allow me to fetch a list of people subscribed to me so I can give people perks on other mediums. Now I have to do it manually.

**Comment by Timtendo12** [comment]
I see "User Subscriptions" but I don't think this is the same as creator subscribers.

**Comment by Rishikant181** [comment]
Checking it now

**Comment by Rishikant181** [comment]
I don't have a creator's account using which I can reverse engineer :(
