### ISSUE TITLE
Get API_KEY with rettiwt auth login ... failed.

### ISSUE THREAD

**Issue by genshindev325** [Rishikant181/Rettiwt-API#571]
Hello
I am very interested in your library and recently I have tried to get API_KEY by using your command step by step. I have created new X account and tried {rettiwt auth login "email" "username" "password"} but failed.
return nothing like this
{}
![Screenshot_1](https://github.com/user-attachments/assets/26c45ac7-0147-4960-ad9f-0bd8140f4304)

I think this is a very easy issue and look forward to your kind response.
Thanks.

**Comment by Rishikant181** [comment]
Do you have 2FA enabled on your Twitter account?
