### ISSUE TITLE
Ability to get commenters

### ISSUE THREAD

**Issue by TheGateKeeper1995** [Rishikant181/Rettiwt-API#576]
Hey friend, I thought it was possible to get a list of people who have commented on a post? I might be tripping, but I can't find the option now and if it is a case that you never had it or you removed it, is it possible to add it in or what is the reason you don't have it?

Looking forward to your response
Thanks in advance

**Comment by Rishikant181** [comment]
Nope, getting list of commenters on a post has never been possible. However, at one point, getting the list of comments was possible, but it was broken and has been deprecated of late.
