### ISSUE TITLE
Bulk Scheduling tweets

### ISSUE THREAD

**Issue by ghost** [Rishikant181/Rettiwt-API#577]
I would like to inquire about the possibility of scheduling tweets. If this feature is currently unavailable, I would like to request its implementation.

**Comment by Rishikant181** [comment]
It has already been requested at #570  and all updates regarding the feature will be tracked there. I'll mark this issue as a duplicate close this one.

**Comment by Rishikant181** [comment]
Duplicate of #570

**Comment by ghost** [comment]
Does this have any limitations, like the number of posts per day?

**Comment by Rishikant181** [comment]
It carries the same rate limits as the Twitter Web App, which I have not tested myself. But, you will face limits if you make too many requests in a minute (no exact figure available). But for use in short bursts, it's alright.

**Comment by ghost** [comment]
Well, I'm going to post 1,500 posts daily. I hope it's under the limit. 🫠
