### ISSUE TITLE
RettiwtError: NOT_FOUND Tweet Fetch

### ISSUE THREAD

**Issue by MDCYT** [Rishikant181/Rettiwt-API#584]
When trying to obtain the data of a tweet it says that it does not exist even though it does, it has been tried with a lot of tweets but each one of the tested ones says that they do not exist, that only affects when obtaining information of a tweet, but it does not affect when obtaining the information of retweets of a tweet.

I am currently using an authenticated account

![imagen](https://github.com/user-attachments/assets/b7fa1868-efb1-44b4-b12c-6dc1d2a7ae17)

**Comment by Rishikant181** [comment]
1. Can you provide me with the ID of a tweet which throws this error?
2. Does the same error occur when fetching the details of a tweet without logging in (i.e, not using an API_KEY)?

**Comment by MDCYT** [comment]
1. 
- https://x.com/jack/status/20 - 20
- https://x.com/Bybit_Official/status/1752950869300244564 - 1752950869300244564
- https://x.com/elonmusk/status/1821415290112209097 - 1821415290112209097

2. Due to some issues I can't check that right now.

**Comment by Rishikant181** [comment]
Strange, it's working as expected on my end. But, the endpoint has a history of causing this issue from time to time, since this endpoint is not exposed directly in the web-app (the web-app uses a different endpoint for fetching details of tweet and it's a wasteful one since it also fetches the replies of the tweets). As a fail-safe, I'll implement the same endpoint as the one used by the web-app.

**Comment by MDCYT** [comment]
Yeah, I think the problem is that Twitter is blocking some of the requests on that Endpoint, it decided to host a copy of my program on another hosting and it works without problems. It must be that Twitter detects that it is a bot and decides not to show it, I suppose, the problem occurs in Railway but not in Bot-hosting.net (Another hosting)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Rishikant181** [comment]
> Twitter detects that it is a bot

Probably this, since the particular endpoint is not even utilized by the Web-App. I'll be switching it to the same endpoint as the one used by Twitter.

**Comment by Rishikant181** [comment]
@MDCYT I pin-pointed the issue: The two endpoints being used under different circumstances:

1. When not logged in, the hidden tweet details endpoint is used.
2. When logged in, the public tweet endpoint is used.

Currently, what Rettiwt-API does is use the hidden endpoint in both cases. However, right now, Twitter does not allow such behavior and requires that those two endpoints be used under different circumstances.

I'm working on the fix now.

**Comment by Rishikant181** [comment]
> the problem occurs in Railway but not in Bot-hosting.net

Something I've notices is that a lot endpoints work weird when hosted on services like Railway, Vercel, etc. AFAIK, cloud platforms like GCP work alright. It needs extensive testing though.

In the meantime, I'm switching over to alternative endpoints.

**Comment by MDCYT** [comment]
It may be possible that the tweet endpoint you use (Hidden) is blocked almost automatically if it detects hosting provider IPs, to avoid scraping bots.

Maybe that's why services like Vercel, Railway, Heroku, etc. are blocked, but services like the one you mention or Bot-Hosting (which I'm currently using)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Rishikant181** [comment]
> It may be possible that the tweet endpoint you use (Hidden)

Remember the debacle when Twitter/X forced people to login to see tweets, which broke the functionality of embedded tweets in websites? This (hidden) endpoint is that endpoint which was setup to make embedded tweets work. That's why it's blocked almost instantaneously if scraper activity is detected, since this endpoint is not meant for logged in users.
