### ISSUE TITLE
rettiwt.user.likes issue

### ISSUE THREAD

**Issue by zk118** [Rishikant181/Rettiwt-API#587]
Hi, the rettiwt.user.likes endpoint just stopped working suddenly, I tried to log-in again - same issue, the response is always empty:

```CursoredData { list: [], next: Cursor { value: '' } }``` 

Any ideas?

**Comment by zk118** [comment]
Well, I just checked, and twitter just removed all my likes, did this happen to anyone?

**Comment by Rishikant181** [comment]
Twitter has removed the ability to see likes, as a result, that method has been [deprecated](https://github.com/Rishikant181/Rettiwt-API/pull/564).

It has been quite some time Twitter/X has implemented [this](https://x.com/elonmusk/status/1800601849973576068).

**Comment by zk118** [comment]
> Twitter has removed the ability to see likes, as a result, that method has been [deprecated](https://github.com/Rishikant181/Rettiwt-API/pull/564)
> 
> It has been quite some time Twitter/X has implemented [this](https://x.com/elonmusk/status/1800601849973576068)

I actually only fetching my own likes. It was working well until today.
I still see my likes when I go to the tweets I liked, but they don't reflect in "My likes" tab. The tab is just empty...

**Comment by Rishikant181** [comment]
If it's empty even on Twitter/X website/app, it's most likely an issue on Twitter/X's end.

On a side note, my likes are still there.

I guess it's just Twitter/X being Twitter/X. It's been on a downward trajectory.

**Comment by zk118** [comment]
Yeah, just contacted their support, thanks for the feedback, closing this.
