### ISSUE TITLE
Reply tweets issues

### ISSUE THREAD

**Issue by liwei-gif** [Rishikant181/Rettiwt-API#588]
Hi, I have a problem when trying to reply to a tweet

it comes up as "undefined".

const { Rettiwt } = require('rettiwt-api');

// Creating a new Rettiwt instance using the given 'API_KEY'
const rettiwt = new Rettiwt({ apiKey: 'API_KEY' });

// Posting a simple text reply, to a tweet with id "1234567890"
rettiwt.tweet.post({ text: 'Great', replyTo: "1765037389800472673" })
.then(res => {
console.log(res);
})
.catch(err => {
console.log(err);
});

I used this example (obviously I replaced API_KEY with the api but I got that error)

How can I fix it?

**Comment by Rishikant181** [comment]
I think that tweet has been removed or hidden or something like that, since fetching the details returns `undefined` too.

**Comment by liwei-gif** [comment]
Curious, now it works for me, maybe it was a temporary Twitter bug, anyway, what a quick response on your part, haha, as soon as I can I'll collaborate on your code :) it's an excellent job

**Comment by Rishikant181** [comment]
> as soon as I can I'll collaborate on your code :)

Ngl, that would be very helpful.
