### ISSUE TITLE
Is there a feature to fetch all tweets by a user?

### ISSUE THREAD

**Issue by improwise** [Rishikant181/Rettiwt-API#594]
Is there currently a feature to just fetch all tweets form a user / profile? The README and the API doc is a bit different in what features are mentioned as already implemented. For example, assume you wanted to fetch all tweets by XDeveloers like https://x.com/XDevelopers. The Twitter Publish widget used to be able to do this but seems to be kind of broken these days based on numerous posts on Reddit etc.

Thanks.

**Comment by Rishikant181** [comment]
No, currently, there is no way to fetch all tweets by a user, except using the `tweet.search` function with the `fromUsers` filter (remember that `tweet.search` is the most reliable and recommended method for fetching tweets), and calling it over and over again, until you run out of search results.
