### ISSUE TITLE
uploading issue 

### ISSUE THREAD

**Issue by IbrahimAbdi1** [Rishikant181/Rettiwt-API#614]
following the example for uploading i get this issue

code:

![image](https://github.com/user-attachments/assets/6f7c5983-21a4-4184-b59b-e1a081150298)

result 

![image](https://github.com/user-attachments/assets/181b934b-8480-47fb-897d-eedb011528fc)

am i doing something wrong here?

**Comment by Rishikant181** [comment]
Oops. This is cause by an incorrect validation rule on my end. Patch is on the way.

**Comment by Rishikant181** [comment]
@IbrahimAbdi1 Please update to v4.1.1 and confirm if it works.

**Comment by Rishikant181** [comment]
@IbrahimAbdi1 Please update to v4.1.1 and confirm whether the issue has been fixed.

**Comment by IbrahimAbdi1** [comment]
yes it works thanks !
