### ISSUE TITLE
Login broken?

### ISSUE THREAD

**Issue by Jeto143** [Rishikant181/Rettiwt-API#621]
Hello,

I see there's already an issue open for login issues, but I noticed this morning that logging in was no longer working at all using either `npx rettiwt login` or `rettiwt-auth user`. In the former case (4.1.1), only `{}` is returned, and in the latter case (2.1.0), I'm getting the following error:

> Error: Failed to authenticate using the given account Credentials
>     at /Users/jeto/Library/pnpm/global/5/.pnpm/rettiwt-auth@2.1.0/node_modules/rettiwt-auth/dist/Auth.js:235:55

The credentials are fine (I've tried with two accounts) and I can see on the corresponding Twitter account that I got a notification that there was an attempt (not a suspicious one though, so they should not be blocking it).

Feel free to close this if it's the same issue as the other ticket, I wasn't entirely sure.

**Comment by Rishikant181** [comment]
Yeah that's the same issue (atleast, they are cause by the same code).

I'm working on that issue. It's just that I have been a bit busy lately. I'm trying to resolve it as fast as I possibly can.
