### ISSUE TITLE
Always returns undefined

### ISSUE THREAD

**Issue by intuixai** [Rishikant181/Rettiwt-API#643]
Hi
I have followed guide, got API key using chrome extension

When I am calling "rettiwt.user.details('bmask_sol')" without API key it says 404 and with API key it always says "undefined"
Please help

Tried on NodeJS 20 & 22 both
Tried on Windows & Ubuntu 20 both

**Comment by Rishikant181** [comment]
That account has been suspended. That's why it returns as such.

![image](https://github.com/user-attachments/assets/1cea0974-98aa-46a8-9500-d0cb3663568d)

**Comment by intuixai** [comment]
Oh, OK. I thought API will return an error if account suspended etc. 
Thanks for quick reply. Thumbs up for a great repo

**Comment by Rishikant181** [comment]
> Thumbs up for a great repo

Glad you found it useful.

> I thought API will return an error if account suspended etc

Let's just say, at the time of writing the code, I wasn't very concerned with proper error messages lol :P
