### ISSUE TITLE
can this api post a msg with photo or media same time ? thanks

### ISSUE THREAD

**Issue by percinor** [Rishikant181/Rettiwt-API#644]
first i use it upload a photo , res return a id , then post a txt msg with this id ,return undefine . and i use this id could not found this photo .if i only post a txt msg, it worked fine.
 rettiwt.tweet.upload('cat.jpg')
.then(res => {
    console.log(res);
})
.catch(err => {
    console.log(err);
});
rettiwt.tweet.post({ text: 'img test!', media: [{ id: '1862505807624929280' }] })
.then(res => {
    console.log(res);
})
.catch(err => {
    console.log(err);
});

**Comment by Rishikant181** [comment]
Strange, that shouldn't be happening. I just tried it and it works. Post the exact text and image from the Twitter web app using the same account?

**Comment by percinor** [comment]
it worked very fine now  ,i wonder how wrong just same code.  anyway ,thank u made so awosome api .
    rettiwt.tweet.upload('beai.png')
    .then(res => {
        console.log(res);
        upimg(res)

    })
    .catch(err => {
        console.log(err);
    });
    function upimg(pa01:string){
        rettiwt.tweet.post({ text: 'upload png from api', media: [{ id: pa01 }] })
    .then(res => {
        console.log(res);
    })
    .catch(err => {
        console.log(err);
    }); 
    }

**Comment by Rishikant181** [comment]
Glad it worked.
